# Generated by Django 2.0.5 on 2018-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, db_index=True, max_length=1024, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=128, null=True)),
                ('followees_count', models.IntegerField(db_index=True, default=0)),
                ('followers_count', models.IntegerField(db_index=True, default=0)),
                ('github_login_name', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('items_count', models.IntegerField(db_index=True, default=0)),
                ('linkedin_id', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('organization', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('permanent_id', models.IntegerField(db_index=True, default=0)),
                ('profile_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('twitter_screen_name', models.CharField(blank=True, max_length=128, null=True)),
                ('website_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
