# Generated by Django 2.0.5 on 2018-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contribution_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
