# Generated by Django 2.0.5 on 2018-05-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0003_user_contribution_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_body', models.CharField(blank=True, max_length=1048576, null=True)),
                ('body', models.CharField(blank=True, max_length=1048576, null=True)),
                ('comments_count', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('item_id', models.CharField(max_length=128, unique=True)),
                ('likes_count', models.IntegerField(db_index=True, default=0)),
                ('reactions_count', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('page_views_count', models.IntegerField(db_index=True, default=0)),
                ('tags', models.ManyToManyField(null=True, to='tecqii.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecqii.User')),
            ],
        ),
    ]
