# Generated by Django 2.0.5 on 2018-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='tecqii.Tag'),
        ),
    ]
