# Generated by Django 2.0.5 on 2018-05-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0005_auto_20180528_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='page_views_count',
        ),
    ]
