# Generated by Django 2.0.5 on 2018-05-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0006_remove_item_page_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTagRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.IntegerField(db_index=True, default=0)),
                ('contribution_count', models.IntegerField(db_index=True, default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecqii.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecqii.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertagrelation',
            unique_together={('user', 'tag')},
        ),
    ]
