# Generated by Django 2.0.5 on 2018-05-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0007_auto_20180528_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, db_index=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
