# Generated by Django 2.0.5 on 2018-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0008_auto_20180529_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_login_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_screen_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
