# Generated by Django 2.0.5 on 2018-05-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecqii', '0009_auto_20180529_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('weight', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecqii.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userkeyword',
            unique_together={('user', 'keyword')},
        ),
    ]
